USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE DATABASE BCAST_PLATFORM_HANDSON;
USE SCHEMA BCAST_PLATFORM_HANDSON.MART;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

SELECT CURRENT_ACCOUNT() AS ACCOUNT_NAME,
       CURRENT_ROLE() AS ROLE_NAME,
       CURRENT_DATABASE() AS DATABASE_NAME,
       CURRENT_WAREHOUSE() AS WAREHOUSE_NAME;

SELECT GENRE,
       COUNT(DISTINCT DEVICE_ID) AS DISTINCT_REACH,
       SUM(SESSION_COUNT) AS TOTAL_SESSIONS,
       SUM(VIEW_MINUTES) AS TOTAL_MINUTES
FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY
WHERE VIEW_DATE >= '2026-07-01'::DATE
  AND VIEW_DATE < '2026-07-31'::DATE
GROUP BY GENRE
ORDER BY GENRE;

WITH fixture (EVENT_ID, DEVICE_ID, NETWORK_ID, GENRE, FROM_TEXT, TO_TEXT) AS (
    SELECT * FROM VALUES
        (1, 'DEMO001', 'NW01', 'NEWS', '2026-07-01 08:00:00', '2026-07-01 08:30:00'),
        (2, 'DEMO001', 'NW01', 'NEWS', '2026-07-01 08:05:00', '2026-07-01 08:10:00'),
        (3, 'DEMO001', 'NW01', 'NEWS', '2026-07-01 08:25:00', '2026-07-01 08:40:00'),
        (4, 'DEMO001', 'NW01', 'NEWS', '2026-07-01 08:40:00', '2026-07-01 08:50:00'),
        (5, 'DEMO001', 'NW01', 'NEWS', '2026-07-01 09:00:00', '2026-07-01 09:10:00'),
        (6, 'DEMO001', 'NW01', 'NEWS', '2026-07-01 09:10:00', '2026-07-01 09:20:00'),
        (7, 'DEMO001', 'NW01', 'NEWS', '2026-07-01 10:00:00', '2026-07-01 10:05:00')
), typed_intervals AS (
    SELECT EVENT_ID, DEVICE_ID, NETWORK_ID, GENRE,
           FROM_TEXT::TIMESTAMP_NTZ AS VIEW_FROM,
           TO_TEXT::TIMESTAMP_NTZ AS VIEW_TO
    FROM fixture
), preceding_bounds AS (
    SELECT *,
           MAX(VIEW_TO) OVER (
               PARTITION BY DEVICE_ID, NETWORK_ID, GENRE
               ORDER BY VIEW_FROM, VIEW_TO, EVENT_ID
               ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
           ) AS PREVIOUS_MAX_TO
    FROM typed_intervals
), boundaries AS (
    SELECT *,
           CASE WHEN PREVIOUS_MAX_TO IS NULL OR VIEW_FROM > PREVIOUS_MAX_TO
                THEN 1 ELSE 0 END AS NEW_GROUP
    FROM preceding_bounds
), numbered AS (
    SELECT *,
           SUM(NEW_GROUP) OVER (
               PARTITION BY DEVICE_ID, NETWORK_ID, GENRE
               ORDER BY VIEW_FROM, VIEW_TO, EVENT_ID
               ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
           ) AS INTERVAL_GROUP
    FROM boundaries
), folded AS (
    SELECT DEVICE_ID, NETWORK_ID, GENRE,
           MIN(VIEW_FROM) AS VIEW_FROM,
           MAX(VIEW_TO) AS VIEW_TO,
           COUNT(*) AS SOURCE_ROWS
    FROM numbered
    GROUP BY DEVICE_ID, NETWORK_ID, GENRE, INTERVAL_GROUP
)
SELECT DEVICE_ID, NETWORK_ID, GENRE, VIEW_FROM, VIEW_TO, SOURCE_ROWS,
       SUM(SOURCE_ROWS) OVER () AS INPUT_ROWS,
       COUNT(*) OVER () AS FOLDED_ROWS
FROM folded
ORDER BY DEVICE_ID, NETWORK_ID, GENRE, VIEW_FROM;