USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE DATABASE BCAST_PLATFORM_HANDSON;
USE SCHEMA BCAST_PLATFORM_HANDSON.MART;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

SELECT CURRENT_ACCOUNT() AS ACCOUNT_NAME,
       CURRENT_ROLE() AS ROLE_NAME,
       CURRENT_DATABASE() AS DATABASE_NAME,
       CURRENT_WAREHOUSE() AS WAREHOUSE_NAME;

CREATE CORTEX SEARCH SERVICE BCAST_PLATFORM_HANDSON.MART.SVC_GENRE_GUIDE
    ON GUIDE_TEXT
    ATTRIBUTES GENRE
    WAREHOUSE = BCAST_PLATFORM_COMMON_WH
    TARGET_LAG = '1 hour'
    EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
AS
SELECT COLUMN1::VARCHAR AS GENRE,
       COLUMN2::VARCHAR AS GUIDE_TEXT
FROM VALUES
    ('NEWS', 'NEWS ニュース。社会の出来事、地域の話題、政治や経済の動きを伝えるジャンル。教材用の架空説明です。'),
    ('DRAMA', 'DRAMA ドラマ。登場人物の関係や成長を物語として描くジャンル。教材用の架空説明です。'),
    ('VARIETY', 'VARIETY バラエティ。トーク、クイズ、企画などを楽しむジャンル。教材用の架空説明です。'),
    ('ANIME', 'ANIME アニメ。アニメーションで物語やキャラクターを表現するジャンル。教材用の架空説明です。'),
    ('SPORTS', 'SPORTS スポーツ。試合の結果、選手の活躍、競技の解説や中継を扱うジャンル。教材用の架空説明です。');

SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
    'BCAST_PLATFORM_HANDSON.MART.SVC_GENRE_GUIDE',
    '{"query":"試合の結果や選手の活躍を知りたい","columns":["GENRE","GUIDE_TEXT"],"limit":3}'
) AS SEARCH_RESULT;