-- 目的: Parquetファイル8個を内部ステージに置き、局別ログ5表と番組・ラベルの3表へ取り込みます。
-- 前提: 01_01_setup.sqlが完了していること。初回は教材専用のRAW 8表が空の状態で実行します。
-- 上から順に実行し、エラーが出たら止めて講師に確認してください。5局のログはここでは結合しません。
-- 各COPYは独立した取込です。8表まとめての成功・取消ではなく、後のCOPYが失敗しても先に成功した表は残ります。
-- 再実行時はSnowflakeのロード履歴により取込済みの同一ファイルが通常スキップされます。FORCEは追加しません。
-- ファイルや表の内容・版の自動照合は行いません。旧データがある場合や配布ファイルが変わった場合は講師に確認してください。
USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE DATABASE BCAST_PLATFORM_HANDSON;
USE SCHEMA BCAST_PLATFORM_HANDSON.RAW;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

-- FETCHでmainのコピーを更新し、指定した8ファイルだけを内部ステージへコピーします。まだ表への取込ではありません。
ALTER GIT REPOSITORY BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO FETCH;
COPY FILES INTO @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO/branches/main/data/
  FILES = ('viewing_log_nw01.parquet', 'viewing_log_nw02.parquet',
           'viewing_log_nw03.parquet', 'viewing_log_nw04.parquet',
           'viewing_log_nw05.parquet', 'program_master.parquet',
           'program_schedule.parquet', 'device_labels.parquet')
  DETAILED_OUTPUT = TRUE;

-- コピー結果と一覧で上記8ファイルを確認してから、次のCOPYへ進みます。
LIST @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/;

-- COPY INTOは指定ファイルの行を表へ取り込みます。列は名前で対応付け、大文字・小文字を区別しません。
-- FILE_FORMATはセットアップ済みのParquet読取設定、ABORT_STATEMENTは読取エラー時にこのCOPYを中止する指定です。
-- 初回の結果はstatus=LOADED、rows_loaded=195938、errors_seen=0を確認します。残り7表も同じ読み方です。
COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FILES = ('viewing_log_nw01.parquet')
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW02
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FILES = ('viewing_log_nw02.parquet')
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW03
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FILES = ('viewing_log_nw03.parquet')
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW04
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FILES = ('viewing_log_nw04.parquet')
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW05
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FILES = ('viewing_log_nw05.parquet')
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.PROGRAM_MASTER
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FILES = ('program_master.parquet')
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.PROGRAM_SCHEDULE
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FILES = ('program_schedule.parquet')
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/F1_SIGNAL_V2/
  FILES = ('device_labels.parquet')
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;

-- 各COPYの成功を確認し、下の8行でROW_COUNTとEXPECTED_ROWSが一致したら第2章の局別dbtへ進みます。
-- UNION ALLは件数の結果だけを並べます。RAWのログ本体を結合する処理ではありません。
-- 再実行でファイルがスキップされた場合も件数を確認します。件数の一致だけでは内容・版の一致は保証しません。
SELECT 'VIEWING_LOG_NW01' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 195938 AS EXPECTED_ROWS
  FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01
UNION ALL
SELECT 'VIEWING_LOG_NW02', COUNT(*), 184465 FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW02
UNION ALL
SELECT 'VIEWING_LOG_NW03', COUNT(*), 179991 FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW03
UNION ALL
SELECT 'VIEWING_LOG_NW04', COUNT(*), 234324 FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW04
UNION ALL
SELECT 'VIEWING_LOG_NW05', COUNT(*), 255930 FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW05
UNION ALL
SELECT 'PROGRAM_MASTER', COUNT(*), 60 FROM BCAST_PLATFORM_HANDSON.RAW.PROGRAM_MASTER
UNION ALL
SELECT 'PROGRAM_SCHEDULE', COUNT(*), 8747 FROM BCAST_PLATFORM_HANDSON.RAW.PROGRAM_SCHEDULE
UNION ALL
SELECT 'DEVICE_LABELS', COUNT(*), 20000 FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS
ORDER BY TABLE_NAME;