-- ============================================
-- 目的: 教材専用のロール、データベース、計算用ウェアハウス、データ取込先を準備します。
-- 前提: 講師が指定したハンズオン用アカウントで、ACCOUNTADMINを使用できること。
-- 実行方法: 接続先を確認し、上から順に実行してください。エラーが出たら後続へ進まないでください。
-- 同名オブジェクトが別用途で存在する場合は実行しないでください。
-- 完了の目安: 最後のLISTでmainブランチのdataフォルダにあるParquetファイル8個を確認できること。
-- 1. 管理者による専用環境の準備
-- ============================================
-- USE ROLEは、このセッションで「どの権限を使って作業するか」を切り替えます。権限を配るGRANTとは別です。
-- ここではロールや接続設定を準備するためにACCOUNTADMINを使い、準備後は教材専用ロールへ切り替えます。
USE ROLE ACCOUNTADMIN;

-- ロールは権限をまとめる入れ物です。ENGINEERは作成・加工、ANALYSTは集計結果の参照に使います。
-- IF NOT EXISTSは同名ロールがあれば作り直しません。既存の権限を初期化する指定ではありません。
CREATE ROLE IF NOT EXISTS BCAST_PLATFORM_ENGINEER_ROLE;
CREATE ROLE IF NOT EXISTS BCAST_PLATFORM_ANALYST_ROLE;
-- TO ROLE SYSADMINで、SYSADMINが教材ロールの権限を継承する階層を作ります。
-- これは管理用の親子関係であり、現在のユーザーへ教材ロールを直接割り当てる操作ではありません。
GRANT ROLE BCAST_PLATFORM_ENGINEER_ROLE TO ROLE SYSADMIN;
GRANT ROLE BCAST_PLATFORM_ANALYST_ROLE TO ROLE SYSADMIN;

-- CURRENT_USER()は実行中の参加者のユーザー名です。SETで保存し、IDENTIFIERでGRANT先の識別子として使います。
-- TO USERによって本人に2つのロールを直接割り当て、後でUSE ROLEで選べるようにします。
SET current_user_name = (SELECT CURRENT_USER());
GRANT ROLE BCAST_PLATFORM_ENGINEER_ROLE TO USER IDENTIFIER($current_user_name);
GRANT ROLE BCAST_PLATFORM_ANALYST_ROLE TO USER IDENTIFIER($current_user_name);

-- DATABASEは表などを整理する最上位の入れ物、SCHEMAはその中の区画、TABLEはデータを格納する表です。
-- WAREHOUSEはSQLを処理する計算資源（CPU・メモリ等）です。データの永続保存先ではありません。
CREATE DATABASE IF NOT EXISTS BCAST_PLATFORM_HANDSON;
-- XSMALLは計算資源のサイズ。AUTO_SUSPEND=60は非稼働60秒後の停止、AUTO_RESUMEは処理が必要なときの再開です。
-- INITIALLY_SUSPENDEDは作成直後を停止状態にします。停止しても表のデータは消えず、保存料金は別に発生します。
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_COMMON_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
-- USE WAREHOUSEは以後のSQLで使う計算資源の選択です。DBの選択やデータの移動ではありません。
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

-- RAWは受け取ったデータ、NW01〜NW05は局別の加工結果、COMMONは5局の共通集計を置く区画です。
-- MLは学習・予測、MARTは分析向けの定義やアプリ、INTEGRATIONSはGit参照先や取込ファイルの置き場に使います。
-- ここでは区画だけを作るので、成功しても視聴データの表や行はまだ増えません。次に計算資源と権限をそろえます。
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW01;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW02;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW03;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW04;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW05;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.COMMON;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.ML;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.MART;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.INTEGRATIONS;

-- 局別処理をそれぞれのWHで動かすと、他局や共通処理と計算資源を分けられます。保存先のスキーマとは別の指定です。
-- 最後のCOMMON_WHは上で作成済みならそのまま残ります。IF NOT EXISTSでは既存WHのサイズや停止設定は変更しません。
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW01_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW02_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW03_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW04_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW05_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_COMMON_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- ============================================
-- 2. エンジニアの作成権限とアナリストの参照権限
-- 後続の表などは作成したロールが所有します。利用者の既定ロール・既定ウェアハウスは変更しません。
-- ============================================
-- DATABASEのUSAGEは、そのDB内のオブジェクトを使うための入口です。これだけで表の中身を読めるわけではありません。
-- 表の参照にはDBとSCHEMAのUSAGEに加え、その表のSELECTが必要です。処理に使うWHのUSAGEも別途付けます。
GRANT USAGE ON DATABASE BCAST_PLATFORM_HANDSON TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON DATABASE BCAST_PLATFORM_HANDSON TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

-- スキーマごとのCREATE権限は「その区画で何を作れるか」です。RAWでは表、NW/COMMONではdbtの加工物を作ります。
-- MLではモデルやNotebook、MARTでは分析ビューやAgentを作るため、区画の用途に合わせて権限を分けています。
GRANT USAGE, CREATE TABLE ON SCHEMA BCAST_PLATFORM_HANDSON.RAW TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW01 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW02 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW03 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW04 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW05 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE MODEL, CREATE NOTEBOOK, CREATE STAGE
  ON SCHEMA BCAST_PLATFORM_HANDSON.ML TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE SEMANTIC VIEW, CREATE AGENT, CREATE STREAMLIT, CREATE STAGE
  ON SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE GIT REPOSITORY, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA BCAST_PLATFORM_HANDSON.INTEGRATIONS TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;

-- ENGINEERには全局と共通のWH、ANALYSTには分析で使う共通WHの利用を許可します。
-- WHのUSAGEは計算資源を使う権限であり、RAWやMLのデータを読む権限にはなりません。
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW01_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW02_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW03_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW04_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW05_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_COMMON_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_COMMON_WH TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

-- ANALYSTの参照先はCOMMONとMARTです。ALLは今ある表・ビュー、FUTUREはこの後に作られる表・ビューが対象です。
-- 片方だけでは既存分か新規分が漏れるため、両方を付けます。スキーマのUSAGEだけではSELECTの代わりになりません。
GRANT USAGE ON SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT USAGE ON SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

-- CORTEX_USERはCortex機能を利用するためのデータベースロールです。教材の表へのSELECTとは別の権限です。
-- ここまでのGRANTが成功したら権限の準備は完了です。データ取込はまだ行わず、次にGitへの接続を許可します。
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

-- ============================================
-- 3. Git API統合: Snowflakeから教材の公開リポジトリに接続するための設定です。
-- 接続を許可するURLは、この教材のリポジトリだけに限定します。
-- ============================================
-- API INTEGRATIONは外部Gitへの接続ルールです。作成だけではGitのファイル取得も表への取込も行われません。
-- 作成とUSAGEの付与が成功したら、ENGINEERが後段でこの接続ルールを使って教材リポジトリを登録できます。
CREATE API INTEGRATION IF NOT EXISTS BCAST_PLATFORM_GIT_API
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-kenokizono/broadcast-data-platform-handson-ja.git')
  ENABLED = TRUE;
GRANT USAGE ON INTEGRATION BCAST_PLATFORM_GIT_API TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;

-- ============================================
-- 4. 空のRAWテーブルと内部ステージ
-- ============================================
-- ここからはENGINEERの権限で作成し、新しい表などをこのロールの所有物にします。
-- SECONDARY ROLES NONEは他の有効ロールの権限に頼らず作業する指定です。管理者権限で不足を見落とすのを防ぎます。
-- 以下のUSEは現在のセッションだけの選択です。ユーザーの既定ロール・既定WHを変更する設定ではありません。
USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE DATABASE BCAST_PLATFORM_HANDSON;
USE SCHEMA BCAST_PLATFORM_HANDSON.RAW;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

-- 視聴ログの1行は、ある端末の視聴開始から終了までの区間です。局・端末・時間・開始時のジャンルを保持します。
-- このCREATEは列名と型を決めるだけです。初回は空の表ができ、01_02_load_parquet.sqlで初めて行が入ります。
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01 (
  EVENT_ID VARCHAR,
  NETWORK_ID VARCHAR,
  DEVICE_ID VARCHAR,
  VIEW_FROM TIMESTAMP_NTZ,
  VIEW_TO TIMESTAMP_NTZ,
  GENRE VARCHAR
);
-- LIKEはNW01と同じ列・型の空の表を作ります。NW01にデータがあっても、その行を他局へコピーしません。
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW02
  LIKE BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01;
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW03
  LIKE BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01;
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW04
  LIKE BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01;
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW05
  LIKE BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01;
-- LABEL_AVAILABLEは正解ラベルを使えるかを示す真偽値です。TRUEの端末だけTARGET_F1に0または1を持ちます。
-- TARGET_F1=1は合成世帯にF1層（20〜34歳女性）がいる端末、0はいないと分かっている端末です。単身世帯も含みます。
-- FALSEの端末は正解が不明なのでTARGET_F1=NULL。NULLを0にすると「不明」を「いない」と誤って学習させます。
-- このラベルは世帯にF1層がいるかどうかであり、実際に画面を見た人の性年代やF1の視聴人数を示すものではありません。
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS (
  DEVICE_ID VARCHAR,
  LABEL_AVAILABLE BOOLEAN,
  TARGET_F1 INTEGER
);
-- PROGRAM_MASTERは番組の説明、PROGRAM_SCHEDULEはその番組をいつ放送したかを保持します。
-- 同じ番組でも放送日・時間が異なるため、番組そのものの情報と放送回の情報を別の表にします。
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.PROGRAM_MASTER (
  PROGRAM_ID VARCHAR(8),
  PROGRAM_NAME VARCHAR(60),
  NETWORK_ID VARCHAR(4),
  GENRE VARCHAR(20),
  TIME_SLOT VARCHAR(20),
  DURATION_MIN NUMBER(4,0),
  SYNOPSIS VARCHAR(400)
);
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.PROGRAM_SCHEDULE (
  PROGRAM_ID VARCHAR(8),
  NETWORK_ID VARCHAR(4),
  AIR_DATE DATE,
  AIR_FROM TIMESTAMP_NTZ,
  AIR_TO TIMESTAMP_NTZ
);

-- 以下2表は学習用データではなく、01_02_load_parquet.sqlが再実行の安全性を自動確認するための管理表です。参加者は直接編集しません。
-- DATASET_RELEASE_FILESは取込済みの版・行数・内容の照合値を記録し、同じデータを再利用できるかの比較に使います。
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.DATASET_RELEASE_FILES (
  DATASET_VERSION VARCHAR NOT NULL,
  TABLE_NAME VARCHAR NOT NULL,
  FILE_NAME VARCHAR NOT NULL,
  FILE_CONTENT_KEY VARCHAR NOT NULL,
  ROW_COUNT NUMBER(38,0) NOT NULL,
  ROW_FINGERPRINT NUMBER(38,0) NOT NULL,
  LOADED_AT TIMESTAMP_NTZ NOT NULL
);
-- DATASET_LOAD_LOCKは取込処理が管理用の1行を更新し、別の取込と同時にRAWを書き換えないようにするための表です。
-- MERGEはLOCK_ID=1の行がなければ追加します。行の削除や追加でエラーを回避せず、セットアップも同時実行しません。
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.DATASET_LOAD_LOCK (
  LOCK_ID INTEGER NOT NULL,
  LAST_LOADER VARCHAR
);
MERGE INTO BCAST_PLATFORM_HANDSON.RAW.DATASET_LOAD_LOCK AS target
USING (SELECT 1 AS LOCK_ID) AS source ON target.LOCK_ID = source.LOCK_ID
WHEN NOT MATCHED THEN INSERT (LOCK_ID) VALUES (source.LOCK_ID);

-- FILE FORMATはParquetを「どう読むか」の設定です。COMPRESSION=AUTOはZSTD圧縮済みの教材を判別して読みます。
-- ファイルを別の圧縮方式へ再圧縮する指定ではありません。LOGICAL_TYPE等は日時やバイナリの型の解釈に関わります。
CREATE FILE FORMAT IF NOT EXISTS BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET
  TYPE = PARQUET
  COMPRESSION = AUTO
  USE_LOGICAL_TYPE = TRUE
  USE_VECTORIZED_SCANNER = TRUE
  BINARY_AS_TEXT = FALSE;
-- STAGEはファイルの置き場、RAWのTABLEは読み取った行の格納先です。WHはその読取・書込を計算します。
-- 作成成功時点では置き場と読取設定ができただけです。01_02_load_parquet.sqlでファイルを置いてから表へ読み込みます。
CREATE STAGE IF NOT EXISTS BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET');

-- ============================================
-- 5. 公開リポジトリに接続し、使用するデータを確認します。
-- FETCHは必須です。Snowflake側のリポジトリ情報を取得してからLISTを実行してください。
-- GitHubのリポジトリは用意済みです。下のCREATEは、Snowflake側に取込用の参照先を作ります。
-- branches/main/data/は、取得したmainブランチのdataフォルダを指します。LISTは一覧表示だけで、取込は行いません。
-- Parquetが8個（局別ログ5、番組マスタ1、放送予定1、ラベル1）あることを確認します。
-- FETCH・LIST・ファイル読取でエラーが出たら、表示内容を確認して講師に連絡してください。
-- 8ファイルを確認できたら、第1章に沿ってGit Workspaceを作り、その中で01_02_load_parquet.sqlを開きます。
-- ============================================
-- このGIT REPOSITORYはSQLが参照するSnowflake内のGitコピーです。SQL等を開いて編集するGit Workspaceとは別です。
-- FETCHはそのコピーを更新します。01_02_load_parquet.sqlの取込元はbranches/main/data/なので、Workspace内の未反映の編集は読みません。
CREATE GIT REPOSITORY IF NOT EXISTS BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO
  API_INTEGRATION = BCAST_PLATFORM_GIT_API
  ORIGIN = 'https://github.com/sfc-gh-kenokizono/broadcast-data-platform-handson-ja.git';
ALTER GIT REPOSITORY BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO FETCH;
LIST @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO/branches/main/data/;