-- ============================================
-- 目的: 教材専用のロール、データベース、計算用ウェアハウス、データ取込先を準備します。
-- 前提: 講師が指定したハンズオン用アカウントで、ACCOUNTADMINを使用できること。
-- 実行方法: 接続先を確認し、上から順に実行してください。エラーが出たら後続へ進まないでください。
-- 同名オブジェクトが別用途で存在する場合は実行しないでください。
-- 完了の目安: 最後のLISTでmainブランチのdataフォルダにあるParquetファイル8個を確認できること。
-- 1. 管理者による専用環境の準備
-- ============================================
USE ROLE ACCOUNTADMIN;

-- 作成・加工用と分析・参照用のロールを用意し、現在の参加者に割り当てます。
CREATE ROLE IF NOT EXISTS BCAST_PLATFORM_ENGINEER_ROLE;
CREATE ROLE IF NOT EXISTS BCAST_PLATFORM_ANALYST_ROLE;
GRANT ROLE BCAST_PLATFORM_ENGINEER_ROLE TO ROLE SYSADMIN;
GRANT ROLE BCAST_PLATFORM_ANALYST_ROLE TO ROLE SYSADMIN;

SET current_user_name = (SELECT CURRENT_USER());
GRANT ROLE BCAST_PLATFORM_ENGINEER_ROLE TO USER IDENTIFIER($current_user_name);
GRANT ROLE BCAST_PLATFORM_ANALYST_ROLE TO USER IDENTIFIER($current_user_name);

CREATE DATABASE IF NOT EXISTS BCAST_PLATFORM_HANDSON;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_COMMON_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

-- RAWは取込元、NW01〜NW05は局別加工、COMMONは共通集計、MLは機械学習、MARTは分析用です。
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW01;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW02;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW03;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW04;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.NW05;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.COMMON;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.ML;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.MART;
CREATE SCHEMA IF NOT EXISTS BCAST_PLATFORM_HANDSON.INTEGRATIONS;

-- 局別の処理と共通処理の計算資源を分けます。未使用時は60秒で自動停止します。
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW01_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW02_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW03_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW04_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_NW05_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS BCAST_PLATFORM_COMMON_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- ============================================
-- 2. エンジニアの作成権限とアナリストの参照権限
-- 後続の表などは作成したロールが所有します。利用者の既定ロール・既定ウェアハウスは変更しません。
-- ============================================
GRANT USAGE ON DATABASE BCAST_PLATFORM_HANDSON TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON DATABASE BCAST_PLATFORM_HANDSON TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

GRANT USAGE, CREATE TABLE ON SCHEMA BCAST_PLATFORM_HANDSON.RAW TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW01 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW02 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW03 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW04 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.NW05 TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE DBT PROJECT
  ON SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE MODEL, CREATE NOTEBOOK, CREATE STAGE
  ON SCHEMA BCAST_PLATFORM_HANDSON.ML TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE SEMANTIC VIEW, CREATE AGENT, CREATE STREAMLIT, CREATE STAGE
  ON SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE, CREATE GIT REPOSITORY, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA BCAST_PLATFORM_HANDSON.INTEGRATIONS TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;

GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW01_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW02_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW03_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW04_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_NW05_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_COMMON_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_COMMON_WH TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

GRANT USAGE ON SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT USAGE ON SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

-- ============================================
-- 3. Git API統合: Snowflakeから教材の公開リポジトリに接続するための設定です。
-- 接続を許可するURLは、この教材のリポジトリだけに限定します。
-- ============================================
CREATE API INTEGRATION IF NOT EXISTS BCAST_PLATFORM_GIT_API
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-kenokizono/broadcast-data-platform-handson-ja.git')
  ENABLED = TRUE;
GRANT USAGE ON INTEGRATION BCAST_PLATFORM_GIT_API TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;

-- ============================================
-- 4. 空のRAWテーブルと内部ステージ
-- ============================================
USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE DATABASE BCAST_PLATFORM_HANDSON;
USE SCHEMA BCAST_PLATFORM_HANDSON.RAW;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01 (
  EVENT_ID VARCHAR,
  NETWORK_ID VARCHAR,
  DEVICE_ID VARCHAR,
  VIEW_FROM TIMESTAMP_NTZ,
  VIEW_TO TIMESTAMP_NTZ,
  GENRE VARCHAR
);
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW02
  LIKE BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01;
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW03
  LIKE BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01;
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW04
  LIKE BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01;
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW05
  LIKE BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01;
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS (
  DEVICE_ID VARCHAR,
  LABEL_AVAILABLE BOOLEAN,
  TARGET_F1 INTEGER
);
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.PROGRAM_MASTER (
  PROGRAM_ID VARCHAR(8),
  PROGRAM_NAME VARCHAR(60),
  NETWORK_ID VARCHAR(4),
  GENRE VARCHAR(20),
  TIME_SLOT VARCHAR(20),
  DURATION_MIN NUMBER(4,0),
  SYNOPSIS VARCHAR(400)
);
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.PROGRAM_SCHEDULE (
  PROGRAM_ID VARCHAR(8),
  NETWORK_ID VARCHAR(4),
  AIR_DATE DATE,
  AIR_FROM TIMESTAMP_NTZ,
  AIR_TO TIMESTAMP_NTZ
);

-- 取込ファイルの版・件数・内容の照合値を記録し、別のデータとの混在を防ぎます。
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.DATASET_RELEASE_FILES (
  DATASET_VERSION VARCHAR NOT NULL,
  TABLE_NAME VARCHAR NOT NULL,
  FILE_NAME VARCHAR NOT NULL,
  FILE_CONTENT_KEY VARCHAR NOT NULL,
  ROW_COUNT NUMBER(38,0) NOT NULL,
  ROW_FINGERPRINT NUMBER(38,0) NOT NULL,
  LOADED_AT TIMESTAMP_NTZ NOT NULL
);
-- データ取込が重なったときに、同時に表を書き換えないための管理用テーブルです。
CREATE TABLE IF NOT EXISTS BCAST_PLATFORM_HANDSON.RAW.DATASET_LOAD_LOCK (
  LOCK_ID INTEGER NOT NULL,
  LAST_LOADER VARCHAR
);
MERGE INTO BCAST_PLATFORM_HANDSON.RAW.DATASET_LOAD_LOCK AS target
USING (SELECT 1 AS LOCK_ID) AS source ON target.LOCK_ID = source.LOCK_ID
WHEN NOT MATCHED THEN INSERT (LOCK_ID) VALUES (source.LOCK_ID);

-- Parquetの日時などの型を読み取る設定と、ファイルを一時的に置く内部ステージを用意します。
CREATE FILE FORMAT IF NOT EXISTS BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET
  TYPE = PARQUET
  COMPRESSION = AUTO
  USE_LOGICAL_TYPE = TRUE
  USE_VECTORIZED_SCANNER = TRUE
  BINARY_AS_TEXT = FALSE;
CREATE STAGE IF NOT EXISTS BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
  FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET');

-- ============================================
-- 5. 公開リポジトリに接続し、使用するデータを確認します。
-- FETCHは必須です。Snowflake側のリポジトリ情報を取得してからLISTを実行してください。
-- GitHubのリポジトリは用意済みです。下のCREATEは、Snowflake側に取込用の参照先を作ります。
-- branches/main/data/は、取得したmainブランチのdataフォルダを指します。LISTは一覧表示だけで、取込は行いません。
-- Parquetが8個（局別ログ5、番組マスタ1、放送予定1、ラベル1）あることを確認します。
-- FETCH・LIST・ファイル読取でエラーが出たら、表示内容を確認して講師に連絡してください。
-- 8ファイルを確認できたら、第1章に沿ってGit Workspaceを作り、その中で02_load_parquet.sqlを開きます。
-- ============================================
CREATE GIT REPOSITORY IF NOT EXISTS BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO
  API_INTEGRATION = BCAST_PLATFORM_GIT_API
  ORIGIN = 'https://github.com/sfc-gh-kenokizono/broadcast-data-platform-handson-ja.git';
ALTER GIT REPOSITORY BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO FETCH;
LIST @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO/branches/main/data/;