-- 目的: COMMONに作成された最終結果を、分かりやすい3つのSELECTで確認します。
-- 前提: 5局すべてとCOMMONのdbt Buildが、エラー0件で完了していること。
-- このSQLは結果を読み取るだけで、テーブルの作成・更新は行いません。
USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

-- 1. 共通の日次表を確認します。結果は1行です。
-- 期待値:
--   MART_ROWS=1,045,120 / REACH_DEVICES=20,000 / TOTAL_SESSIONS=1,050,000
--   TOTAL_MINUTES=約12,511,642.266667 / 期間=2026-05-01〜2026-07-31 / GENRES=8
SELECT COUNT(*) AS MART_ROWS,
       COUNT(DISTINCT DEVICE_ID) AS REACH_DEVICES,
       SUM(SESSION_COUNT) AS TOTAL_SESSIONS,
       SUM(VIEW_MINUTES) AS TOTAL_MINUTES,
       MIN(VIEW_DATE) AS FIRST_DATE,
       MAX(VIEW_DATE) AS LAST_DATE,
       COUNT(DISTINCT GENRE) AS GENRES
FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY;

-- 2. 共通の毎分表を確認します。結果は1行です。
-- 期待値: MINUTE_MART_ROWS=548,535 / DEVICE_MINUTE_BUCKETS=13,532,927
-- DEVICE_MINUTE_BUCKETSは、各1分枠で視聴していた端末数を合計した値です。
SELECT COUNT(*) AS MINUTE_MART_ROWS,
       SUM(VIEWING_DEVICES) AS DEVICE_MINUTE_BUCKETS
FROM BCAST_PLATFORM_HANDSON.COMMON.MINUTE_AUDIENCE;

-- 3. ラベル表と視聴データの端末IDが対応しているか確認します。結果は1行です。
-- 期待値: 両方とも0
WITH observed AS (
  SELECT DISTINCT DEVICE_ID
  FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY
)
SELECT COALESCE(COUNT_IF(observed.DEVICE_ID IS NULL), 0)
         AS LABEL_DEVICES_WITHOUT_OBSERVATIONS,
       COALESCE(COUNT_IF(labels.DEVICE_ID IS NULL), 0)
         AS OBSERVED_DEVICES_WITHOUT_LABEL_ROW
FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS AS labels
FULL OUTER JOIN observed
  ON labels.DEVICE_ID = observed.DEVICE_ID;