-- 目的: 局別の加工結果とCOMMONの共通集計が一致しているかを確認します。表の作成・更新は行いません。
-- 前提: データ取込と、5局すべて・COMMONのdbtビルドおよびテストが完了していること。
-- 実行方法: ハンズオン用アカウントで上から順に実行し、EXECUTE IMMEDIATEの各ブロックはまとめて実行します。
-- 確認順: 日次全体1行 → 毎分全体1行 → COMMON照合 → 局別照合5行 → 局・日別集計 → ラベル対応1行。
-- 完了の目安: エラーがなく、全体の値と各差分が下記の条件を満たすこと。
-- エラーが出た場合はMLやアプリへ進まず、各局とCOMMONのビルド・テスト結果を講師と確認してください。
USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

-- 共通の日次表の行数、重複を除いた端末数、視聴回数・時間、期間、ジャンル数を確認します。
-- MART_ROWSは集計表の行数です。視聴回数はTOTAL_SESSIONSで確認してください。
-- 結果は1行です。期間2026-05-01〜2026-07-31・8ジャンルを確認し、件数と時間は次の照合で局別表と比較します。
SELECT COUNT(*) AS MART_ROWS, COUNT(DISTINCT DEVICE_ID) AS REACH_DEVICES,
       SUM(SESSION_COUNT) AS TOTAL_SESSIONS, SUM(VIEW_MINUTES) AS TOTAL_MINUTES,
       MIN(VIEW_DATE) AS FIRST_DATE, MAX(VIEW_DATE) AS LAST_DATE,
       COUNT(DISTINCT GENRE) AS GENRES
FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY;

-- 共通の毎分表全体を1行で確認します。MINUTE_MART_ROWS=548,535、DEVICE_MINUTE_BUCKETS=13,532,927が期待値です。
-- DEVICE_MINUTE_BUCKETSは局・端末・分の組の延べ数で、全期間リーチや実視聴の経過分数ではありません。
SELECT COUNT(*) AS MINUTE_MART_ROWS,
       SUM(VIEWING_DEVICES) AS DEVICE_MINUTE_BUCKETS
FROM BCAST_PLATFORM_HANDSON.COMMON.MINUTE_AUDIENCE;

-- 日次表と毎分表について、5局の合計がCOMMONと一致するかを確認します。
-- 空の表や指標のNULLも検出します。集計が途中の状態で後続へ進まないための確認です。
-- WHEREは不一致だけを拾います。内部のmismatches=0が成功で、異常があれば例外で停止します。成功明細は表示しません。
EXECUTE IMMEDIATE $$
DECLARE
  reconciliation_failed EXCEPTION (-20009, 'COMMON reconciliation failed. Stop: rebuild and test all station and COMMON tables before ML or app.');
  mismatches INTEGER;
BEGIN
-- 日次表: expectedは5局の合計、actualはCOMMONです。行数・回数は一致、時間は小数の許容誤差内なら通過します。
WITH station_totals AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(SESSION_COUNT) AS SESSIONS, SUM(VIEW_MINUTES) AS MINUTES,
         COUNT(*) - COUNT(SESSION_COUNT) + COUNT(*) - COUNT(VIEW_MINUTES) AS INVALID_ROWS
  FROM BCAST_PLATFORM_HANDSON.NW01.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES), COUNT(*) - COUNT(SESSION_COUNT) + COUNT(*) - COUNT(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW02.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES), COUNT(*) - COUNT(SESSION_COUNT) + COUNT(*) - COUNT(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW03.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES), COUNT(*) - COUNT(SESSION_COUNT) + COUNT(*) - COUNT(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW04.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES), COUNT(*) - COUNT(SESSION_COUNT) + COUNT(*) - COUNT(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW05.MART_DEVICE_DAILY
), expected AS (
  SELECT SUM(ROWS_COUNT) AS ROWS_COUNT, SUM(SESSIONS) AS SESSIONS, SUM(MINUTES) AS MINUTES,
         SUM(INVALID_ROWS) AS INVALID_ROWS, MIN(ROWS_COUNT) AS MIN_STATION_ROWS
  FROM station_totals
), actual AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(SESSION_COUNT) AS SESSIONS, SUM(VIEW_MINUTES) AS MINUTES,
         COUNT(*) - COUNT(SESSION_COUNT) + COUNT(*) - COUNT(VIEW_MINUTES) AS INVALID_ROWS
  FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY
)
SELECT COUNT(*) INTO :mismatches FROM actual CROSS JOIN expected
WHERE expected.MIN_STATION_ROWS = 0 OR actual.ROWS_COUNT = 0
   OR expected.INVALID_ROWS > 0 OR actual.INVALID_ROWS > 0
   OR actual.ROWS_COUNT IS DISTINCT FROM expected.ROWS_COUNT
   OR actual.SESSIONS IS DISTINCT FROM expected.SESSIONS
   OR expected.MINUTES IS NULL OR actual.MINUTES IS NULL
   OR ABS(actual.MINUTES - expected.MINUTES) > GREATEST(0.000001, ABS(expected.MINUTES) * 0.000000001);
IF (mismatches != 0) THEN
  RAISE reconciliation_failed;
END IF;

-- 毎分表: 各分の端末数を足した「端末分数」と行数を照合します。同じ端末を分ごとに数えるため、リーチとは違います。
WITH station_totals AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(VIEWING_DEVICES) AS DEVICE_MINUTES,
         COUNT(*) - COUNT(VIEWING_DEVICES) AS INVALID_ROWS FROM BCAST_PLATFORM_HANDSON.NW01.MART_MINUTE_AUDIENCE
  UNION ALL SELECT COUNT(*), SUM(VIEWING_DEVICES), COUNT(*) - COUNT(VIEWING_DEVICES) FROM BCAST_PLATFORM_HANDSON.NW02.MART_MINUTE_AUDIENCE
  UNION ALL SELECT COUNT(*), SUM(VIEWING_DEVICES), COUNT(*) - COUNT(VIEWING_DEVICES) FROM BCAST_PLATFORM_HANDSON.NW03.MART_MINUTE_AUDIENCE
  UNION ALL SELECT COUNT(*), SUM(VIEWING_DEVICES), COUNT(*) - COUNT(VIEWING_DEVICES) FROM BCAST_PLATFORM_HANDSON.NW04.MART_MINUTE_AUDIENCE
  UNION ALL SELECT COUNT(*), SUM(VIEWING_DEVICES), COUNT(*) - COUNT(VIEWING_DEVICES) FROM BCAST_PLATFORM_HANDSON.NW05.MART_MINUTE_AUDIENCE
), expected AS (
  SELECT SUM(ROWS_COUNT) AS ROWS_COUNT, SUM(DEVICE_MINUTES) AS DEVICE_MINUTES,
         SUM(INVALID_ROWS) AS INVALID_ROWS, MIN(ROWS_COUNT) AS MIN_STATION_ROWS FROM station_totals
), actual AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(VIEWING_DEVICES) AS DEVICE_MINUTES,
         COUNT(*) - COUNT(VIEWING_DEVICES) AS INVALID_ROWS
  FROM BCAST_PLATFORM_HANDSON.COMMON.MINUTE_AUDIENCE
)
SELECT COUNT(*) INTO :mismatches FROM actual CROSS JOIN expected
WHERE expected.MIN_STATION_ROWS = 0 OR actual.ROWS_COUNT = 0
   OR expected.INVALID_ROWS > 0 OR actual.INVALID_ROWS > 0
   OR actual.ROWS_COUNT IS DISTINCT FROM expected.ROWS_COUNT
   OR expected.DEVICE_MINUTES IS NULL OR actual.DEVICE_MINUTES IS NULL
   OR actual.DEVICE_MINUTES IS DISTINCT FROM expected.DEVICE_MINUTES;
IF (mismatches != 0) THEN
  RAISE reconciliation_failed;
END IF;
END;
$$;

-- 局ごとにRAWから期待値を計算し、整形済み・日次・毎分の各表と照合します。
-- RAWの全局結合やテーブル作成は行いません。RAW件数には不正区間と完全重複が含まれます。
-- ACTUAL_METRICS内の*_DIFFERENCEが0であることを確認してください。
-- 視聴時間の小数計算には丸め誤差があるため、絶対差1e-6または相対差1e-9の大きい方まで許容します。
-- 結果はNW01〜NW05の5行です。INVALID_ROWSやVALID_DUPLICATE_ROWSはRAWから除く対象なので、0でなくても異常ではありません。
-- 確認するのは除去・集計後の差分です。ここでいうmetricsは加工結果の照合値で、MLの精度評価ではありません。
EXECUTE IMMEDIATE $$
DECLARE
  metrics ARRAY DEFAULT ARRAY_CONSTRUCT();
  raw_table VARCHAR;
  clean_table VARCHAR;
  daily_table VARCHAR;
  minutes_table VARCHAR;
  audience_table VARCHAR;
  station_metrics OBJECT;
  reconciliation_failed EXCEPTION (-20008, 'Station reconciliation failed. Stop: do not proceed to ML or app. Run all station dbt builds/tests and then common build/tests.');
  results RESULTSET;
BEGIN
  FOR station IN 1 TO 5 DO
    raw_table := 'BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW0' || station;
    clean_table := 'BCAST_PLATFORM_HANDSON.NW0' || station || '.CLEAN_VIEWING';
    daily_table := 'BCAST_PLATFORM_HANDSON.NW0' || station || '.MART_DEVICE_DAILY';
    minutes_table := 'BCAST_PLATFORM_HANDSON.NW0' || station || '.VIEWING_MINUTES';
    audience_table := 'BCAST_PLATFORM_HANDSON.NW0' || station || '.MART_MINUTE_AUDIENCE';
    WITH raw_stats AS (
      SELECT COUNT(*) AS RAW_ROWS,
             COALESCE(COUNT_IF(VIEW_FROM IS NULL OR VIEW_TO IS NULL OR VIEW_TO <= VIEW_FROM
                      OR DATEDIFF('nanosecond', VIEW_FROM, VIEW_TO) > 86400000000000), 0) AS INVALID_ROWS
      FROM IDENTIFIER(:raw_table)
    ), valid_distinct AS (
      SELECT DISTINCT EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE
      FROM IDENTIFIER(:raw_table)
      WHERE VIEW_TO > VIEW_FROM AND DATEDIFF('nanosecond', VIEW_FROM, VIEW_TO) <= 86400000000000
    ), expected AS (
      SELECT COUNT(*) AS VALID_DISTINCT_ROWS,
             COALESCE(SUM(DATEDIFF('nanosecond', VIEW_FROM, VIEW_TO)::FLOAT / 60000000000.0), 0) AS ELAPSED_MINUTES,
             COALESCE(SUM(DATEDIFF('minute', DATE_TRUNC('minute', VIEW_FROM),
                                  DATE_TRUNC('minute', DATEADD('nanosecond', -1, VIEW_TO))) + 1), 0) AS EXPECTED_EXPANSION
      FROM valid_distinct
    ), clean AS (
      SELECT COUNT(*) AS CLEAN_ROWS, COUNT(DISTINCT DEVICE_ID) AS DEVICES,
             COUNT(DISTINCT GENRE) AS GENRES, COALESCE(SUM(VIEW_MINUTES), 0) AS CLEAN_MINUTES
      FROM IDENTIFIER(:clean_table)
    ), daily AS (
      SELECT COUNT(*) AS DAILY_ROWS, COALESCE(SUM(SESSION_COUNT), 0) AS SESSIONS,
             COALESCE(SUM(VIEW_MINUTES), 0) AS DAILY_MINUTES FROM IDENTIFIER(:daily_table)
    ), expanded AS (
      SELECT COUNT(*) AS EXPANDED_ROWS FROM IDENTIFIER(:minutes_table)
    ), distinct_device_minutes AS (
      SELECT COUNT(*) AS DISTINCT_DEVICE_MINUTES FROM (
        SELECT DISTINCT NETWORK_ID, DEVICE_ID, MINUTE_AT FROM IDENTIFIER(:minutes_table)
      )
    ), audience AS (
      SELECT COUNT(*) AS AUDIENCE_ROWS, COALESCE(SUM(VIEWING_DEVICES), 0) AS AUDIENCE_DEVICE_MINUTES
      FROM IDENTIFIER(:audience_table)
    )
    SELECT OBJECT_CONSTRUCT(
      'NETWORK_ID', 'NW0' || :station,
      'RAW_ROWS', raw_stats.RAW_ROWS, 'INVALID_ROWS', raw_stats.INVALID_ROWS,
      'VALID_DUPLICATE_ROWS', raw_stats.RAW_ROWS - raw_stats.INVALID_ROWS - expected.VALID_DISTINCT_ROWS,
      'EXPECTED_CLEAN_ROWS', expected.VALID_DISTINCT_ROWS, 'CLEAN_ROWS', clean.CLEAN_ROWS,
      'CLEAN_ROW_DIFFERENCE', clean.CLEAN_ROWS - expected.VALID_DISTINCT_ROWS,
      'DEVICES', clean.DEVICES, 'GENRES', clean.GENRES,
      'DAILY_ROWS', daily.DAILY_ROWS, 'SESSIONS', daily.SESSIONS,
      'SESSION_DIFFERENCE', daily.SESSIONS - clean.CLEAN_ROWS,
      'EXPECTED_ELAPSED_MINUTES', expected.ELAPSED_MINUTES, 'CLEAN_MINUTES', clean.CLEAN_MINUTES,
      'DAILY_MINUTES', daily.DAILY_MINUTES,
      'CLEAN_MINUTE_DIFFERENCE', clean.CLEAN_MINUTES - expected.ELAPSED_MINUTES,
      'DAILY_MINUTE_DIFFERENCE', daily.DAILY_MINUTES - clean.CLEAN_MINUTES,
      'EXPECTED_EXPANSION', expected.EXPECTED_EXPANSION, 'EXPANDED_ROWS', expanded.EXPANDED_ROWS,
      'EXPANSION_DIFFERENCE', expanded.EXPANDED_ROWS - expected.EXPECTED_EXPANSION,
      'AUDIENCE_ROWS', audience.AUDIENCE_ROWS,
      'DISTINCT_DEVICE_MINUTES', distinct_device_minutes.DISTINCT_DEVICE_MINUTES,
      'AUDIENCE_DEVICE_MINUTES', audience.AUDIENCE_DEVICE_MINUTES,
      'AUDIENCE_DIFFERENCE', audience.AUDIENCE_DEVICE_MINUTES - distinct_device_minutes.DISTINCT_DEVICE_MINUTES
    ) INTO :station_metrics
    FROM raw_stats CROSS JOIN expected CROSS JOIN clean CROSS JOIN daily CROSS JOIN expanded
    CROSS JOIN distinct_device_minutes CROSS JOIN audience;
    IF (station_metrics:EXPECTED_CLEAN_ROWS::NUMBER = 0
        OR station_metrics:CLEAN_ROW_DIFFERENCE::NUMBER != 0
        OR station_metrics:SESSION_DIFFERENCE::NUMBER != 0
        OR station_metrics:EXPANSION_DIFFERENCE::NUMBER != 0
        OR station_metrics:AUDIENCE_DIFFERENCE::NUMBER != 0
        OR ABS(station_metrics:CLEAN_MINUTE_DIFFERENCE::DOUBLE) > GREATEST(0.000001, ABS(station_metrics:EXPECTED_ELAPSED_MINUTES::DOUBLE) * 0.000000001)
        OR ABS(station_metrics:DAILY_MINUTE_DIFFERENCE::DOUBLE) > GREATEST(0.000001, ABS(station_metrics:CLEAN_MINUTES::DOUBLE) * 0.000000001)) THEN
      RAISE reconciliation_failed;
    END IF;
    metrics := ARRAY_APPEND(metrics, station_metrics);
  END FOR;
  results := (SELECT VALUE:NETWORK_ID::VARCHAR AS NETWORK_ID, VALUE AS ACTUAL_METRICS
              FROM TABLE(FLATTEN(INPUT => :metrics)) ORDER BY NETWORK_ID);
  RETURN TABLE(results);
END;
$$;

-- 局別・日別に、観測された分の数とピーク時の端末数を確認します。
-- 分内視聴端末数の総和は「端末分数」です。全期間リーチや実視聴の経過分数とは別の指標です。
-- これは異常行の抽出ではなく、正常時にも局・日ごとの行が出る集計です。観測分数を必ず1,440とみなさないでください。
SELECT NETWORK_ID, VIEW_DATE, COUNT(*) AS OBSERVED_MINUTE_BUCKETS,
       MIN(MINUTE_AT) AS FIRST_MINUTE, MAX(MINUTE_AT) AS LAST_MINUTE,
       MAX(VIEWING_DEVICES) AS PEAK_MINUTE_DEVICES,
       SUM(VIEWING_DEVICES) AS DEVICE_MINUTE_BUCKETS
FROM BCAST_PLATFORM_HANDSON.COMMON.MINUTE_AUDIENCE
GROUP BY NETWORK_ID, VIEW_DATE ORDER BY VIEW_DATE, NETWORK_ID;

-- ラベル表と視聴データの端末IDを突き合わせます。両方の結果が0であることを確認してください。
-- ラベル行があることと、正解ラベルを利用できること（LABEL_AVAILABLE）は異なります。
-- 左の数値は「ラベル表にだけいる端末」、右は「視聴表にだけいる端末」の数です。結果1行の両列が0なら対応しています。
-- 上の全検査が成功してから次章へ進みます。ラベル不明の端末を0扱いにしたり、差分のあるままML・アプリへ進めません。
WITH observed AS (
  SELECT DISTINCT DEVICE_ID FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY
)
SELECT COALESCE(COUNT_IF(observed.DEVICE_ID IS NULL), 0) AS LABEL_DEVICES_WITHOUT_OBSERVATIONS,
       COALESCE(COUNT_IF(labels.DEVICE_ID IS NULL), 0) AS OBSERVED_DEVICES_WITHOUT_LABEL_ROW
FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS AS labels
FULL OUTER JOIN observed ON labels.DEVICE_ID = observed.DEVICE_ID;