-- ============================================
-- 公開後の教材用。01_setup.sql完了後に区切って実行する。
-- エラー・ファイル不足があれば、その時点で停止する。
-- ============================================
USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE DATABASE BCAST_PLATFORM_HANDSON;
USE SCHEMA BCAST_PLATFORM_HANDSON.RAW;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

ALTER GIT REPOSITORY BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO FETCH;
COPY FILES INTO @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO/branches/main/data/
  FILES = ('viewing_log_nw01.parquet', 'viewing_log_nw02.parquet',
           'viewing_log_nw03.parquet', 'viewing_log_nw04.parquet',
           'viewing_log_nw05.parquet', 'device_labels.parquet')
  DETAILED_OUTPUT = TRUE;

-- COPY FILESは存在しない指定ファイルをスキップする。
-- 上の結果が必ず6行であることを確認してから以下へ進む。
LIST @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE;

-- 日時は論理型を解釈したうえでTIMESTAMP_NTZへ明示的に変換する。
-- 2026年7月の時刻が見えることを確認する。整数のままなら先へ進まない。
SELECT $1:DEVICE_ID::VARCHAR AS DEVICE_ID,
       $1:VIEW_FROM::TIMESTAMP_NTZ AS VIEW_FROM,
       $1:VIEW_TO::TIMESTAMP_NTZ AS VIEW_TO
FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/viewing_log_nw01.parquet
  (FILE_FORMAT => 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
LIMIT 5;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw01.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW02
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw02.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW03
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw03.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW04
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw04.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW05
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw05.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS
  (DEVICE_ID, LABEL_AVAILABLE, TARGET_SPORTS_FAN)
FROM (
  SELECT $1:DEVICE_ID::VARCHAR, $1:LABEL_AVAILABLE::BOOLEAN,
         $1:TARGET_SPORTS_FAN::INTEGER
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('device_labels.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

-- 各局3600行、ラベル200行。再実行でもこの件数であることを確認する。
SELECT 'NW01' AS SOURCE, COUNT(*) AS ROW_COUNT FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01
UNION ALL SELECT 'NW02', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW02
UNION ALL SELECT 'NW03', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW03
UNION ALL SELECT 'NW04', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW04
UNION ALL SELECT 'NW05', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW05
UNION ALL SELECT 'DEVICE_LABELS', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS
ORDER BY SOURCE;

-- 200 / 100 / 100 / 50 / 50 / 0 を期待する。
SELECT COUNT(DISTINCT DEVICE_ID) AS DEVICES,
       COUNT_IF(LABEL_AVAILABLE) AS KNOWN_LABELS,
       COUNT_IF(NOT LABEL_AVAILABLE AND TARGET_SPORTS_FAN IS NULL) AS UNKNOWN_LABELS,
       COUNT_IF(LABEL_AVAILABLE AND TARGET_SPORTS_FAN = 0) AS CLASS_ZERO,
       COUNT_IF(LABEL_AVAILABLE AND TARGET_SPORTS_FAN = 1) AS CLASS_ONE,
       COUNT_IF(NOT LABEL_AVAILABLE AND TARGET_SPORTS_FAN IS NOT NULL) AS LEAKED_TARGETS
FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS;