-- ============================================
-- 公開後の教材用。01_setup.sql完了後に区切って実行する。
-- エラー・ファイル不足があれば、その時点で停止する。
-- ============================================
USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE SECONDARY ROLES NONE;
USE DATABASE BCAST_PLATFORM_HANDSON;
USE SCHEMA BCAST_PLATFORM_HANDSON.RAW;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

-- このブロックを一括実行する。検査失敗時にはCOPY INTOへ進まない。
-- 旧データを自動削除しない。旧局別データがある場合は移行方針を別途確認する。
EXECUTE IMMEDIATE $$
DECLARE
  incompatible_schema EXCEPTION (-20001, 'RAW schema mismatch: expected six viewing columns, original program master/schedule schemas and DEVICE_ID/LABEL_AVAILABLE/TARGET_F1. Stop; do not load the old small sample.');
  incompatible_data EXCEPTION (-20002, 'Existing viewing rows are outside the unified C000001-C020000 May-July 2026 cohort. Stop and review migration separately; no viewing tables are reset here.');
  incompatible_files EXCEPTION (-20003, 'Expected all eight Parquet files and nonempty F1 label data with the new three-column schema. Check main/data and stage before retrying.');
  schema_mismatches INTEGER;
  legacy_rows INTEGER;
  staged_files INTEGER;
  label_rows INTEGER;
  invalid_labels INTEGER;
  panel_rows INTEGER;
  unique_devices INTEGER;
  viewing_table VARCHAR;
BEGIN
  WITH expected AS (
    SELECT 'VIEWING_LOG_' || station.COLUMN1 AS TABLE_NAME,
           definition.COLUMN1 AS COLUMN_NAME, definition.COLUMN2 AS DATA_TYPE
    FROM (VALUES ('NW01'), ('NW02'), ('NW03'), ('NW04'), ('NW05')) AS station
    CROSS JOIN (VALUES ('EVENT_ID', 'TEXT'), ('NETWORK_ID', 'TEXT'), ('DEVICE_ID', 'TEXT'),
                       ('VIEW_FROM', 'TIMESTAMP_NTZ'), ('VIEW_TO', 'TIMESTAMP_NTZ'), ('GENRE', 'TEXT')) AS definition
    UNION ALL
    SELECT COLUMN1, COLUMN2, COLUMN3 FROM VALUES
      ('DEVICE_LABELS', 'DEVICE_ID', 'TEXT'), ('DEVICE_LABELS', 'LABEL_AVAILABLE', 'BOOLEAN'),
      ('DEVICE_LABELS', 'TARGET_F1', 'NUMBER'),
      ('PROGRAM_MASTER', 'PROGRAM_ID', 'TEXT'), ('PROGRAM_MASTER', 'PROGRAM_NAME', 'TEXT'),
      ('PROGRAM_MASTER', 'NETWORK_ID', 'TEXT'), ('PROGRAM_MASTER', 'GENRE', 'TEXT'),
      ('PROGRAM_MASTER', 'TIME_SLOT', 'TEXT'), ('PROGRAM_MASTER', 'DURATION_MIN', 'NUMBER'),
      ('PROGRAM_MASTER', 'SYNOPSIS', 'TEXT'),
      ('PROGRAM_SCHEDULE', 'PROGRAM_ID', 'TEXT'), ('PROGRAM_SCHEDULE', 'NETWORK_ID', 'TEXT'),
      ('PROGRAM_SCHEDULE', 'AIR_DATE', 'DATE'), ('PROGRAM_SCHEDULE', 'AIR_FROM', 'TIMESTAMP_NTZ'),
      ('PROGRAM_SCHEDULE', 'AIR_TO', 'TIMESTAMP_NTZ')
  ), actual AS (
    SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NUMERIC_SCALE
    FROM BCAST_PLATFORM_HANDSON.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'RAW' AND TABLE_NAME IN
      ('VIEWING_LOG_NW01', 'VIEWING_LOG_NW02', 'VIEWING_LOG_NW03', 'VIEWING_LOG_NW04',
       'VIEWING_LOG_NW05', 'DEVICE_LABELS', 'PROGRAM_MASTER', 'PROGRAM_SCHEDULE')
  )
  SELECT COUNT(*) INTO :schema_mismatches
  FROM expected FULL OUTER JOIN actual
    ON expected.TABLE_NAME = actual.TABLE_NAME AND expected.COLUMN_NAME = actual.COLUMN_NAME
  WHERE expected.COLUMN_NAME IS NULL OR actual.COLUMN_NAME IS NULL
     OR expected.DATA_TYPE != actual.DATA_TYPE
     OR (actual.DATA_TYPE = 'NUMBER' AND actual.NUMERIC_SCALE != 0);
  IF (schema_mismatches > 0) THEN
    RAISE incompatible_schema;
  END IF;
  SELECT COUNT(*) INTO :legacy_rows FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS
  WHERE DEVICE_ID IS NULL OR NOT REGEXP_LIKE(DEVICE_ID, 'C[0-9]{6}')
     OR TRY_TO_NUMBER(SUBSTR(DEVICE_ID, 2)) NOT BETWEEN 1 AND 20000
     OR LABEL_AVAILABLE IS NULL
     OR (LABEL_AVAILABLE AND (TARGET_F1 IS NULL OR TARGET_F1 NOT IN (0, 1)))
     OR (NOT LABEL_AVAILABLE AND TARGET_F1 IS NOT NULL);
  IF (legacy_rows > 0) THEN
    RAISE incompatible_data;
  END IF;
  FOR station IN 1 TO 5 DO
    viewing_table := 'BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW0' || station;
    SELECT COUNT(*) INTO :legacy_rows FROM IDENTIFIER(:viewing_table)
    WHERE DEVICE_ID IS NULL OR NOT REGEXP_LIKE(DEVICE_ID, 'C[0-9]{6}')
       OR TRY_TO_NUMBER(SUBSTR(DEVICE_ID, 2)) NOT BETWEEN 1 AND 20000
       OR (VIEW_FROM IS NOT NULL AND (VIEW_FROM < '2026-05-01'::TIMESTAMP_NTZ
                                     OR VIEW_FROM >= '2026-08-01'::TIMESTAMP_NTZ));
    IF (legacy_rows > 0) THEN
      RAISE incompatible_data;
    END IF;
  END FOR;

ALTER GIT REPOSITORY BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO FETCH;
COPY FILES INTO @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_REPO/branches/main/data/
  FILES = ('viewing_log_nw01.parquet', 'viewing_log_nw02.parquet',
           'viewing_log_nw03.parquet', 'viewing_log_nw04.parquet',
           'viewing_log_nw05.parquet', 'program_master.parquet',
           'program_schedule.parquet', 'device_labels.parquet')
  DETAILED_OUTPUT = TRUE;

-- COPY FILESは存在しない指定ファイルをスキップする。
SELECT COUNT(*) INTO :staged_files FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
IF (staged_files != 8) THEN
  RAISE incompatible_files;
END IF;
SELECT IFF(COUNT(*) = 3 AND COUNT_IF(COLUMN_NAME IN ('DEVICE_ID', 'LABEL_AVAILABLE', 'TARGET_F1')) = 3, 0, 1)
INTO :schema_mismatches
FROM TABLE(INFER_SCHEMA(
  LOCATION => '@BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/device_labels.parquet',
  FILE_FORMAT => 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET'
));
IF (schema_mismatches > 0) THEN
  RAISE incompatible_files;
END IF;
SELECT COUNT(*), COUNT_IF(
    COALESCE(ARRAY_CONTAINS('TARGET_SPORTS_FAN'::VARIANT, OBJECT_KEYS($1)), FALSE)
    OR NOT COALESCE(REGEXP_LIKE($1:DEVICE_ID::VARCHAR, 'C[0-9]{6}'), FALSE)
    OR TRY_TO_NUMBER(SUBSTR($1:DEVICE_ID::VARCHAR, 2)) NOT BETWEEN 1 AND 20000
    OR COALESCE(TYPEOF($1:LABEL_AVAILABLE) != 'BOOLEAN', TRUE)
    OR ($1:LABEL_AVAILABLE::BOOLEAN AND ($1:TARGET_F1::INTEGER IS NULL OR $1:TARGET_F1::INTEGER NOT IN (0, 1)))
    OR (NOT $1:LABEL_AVAILABLE::BOOLEAN AND $1:TARGET_F1::INTEGER IS NOT NULL)
) INTO :label_rows, :invalid_labels
FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/device_labels.parquet
  (FILE_FORMAT => 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET');
IF (label_rows = 0 OR invalid_labels > 0) THEN
  RAISE incompatible_files;
END IF;
SELECT COUNT(DISTINCT $1:DEVICE_ID::VARCHAR), COUNT_IF($1:LABEL_AVAILABLE::BOOLEAN)
INTO :unique_devices, :panel_rows
FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/device_labels.parquet
  (FILE_FORMAT => 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET');
IF (label_rows != 20000 OR unique_devices != 20000 OR panel_rows != 2000) THEN
  RAISE incompatible_files;
END IF;

-- 日時は論理型を解釈したうえでTIMESTAMP_NTZへ明示的に変換する。
-- 2026年5〜7月の合成時刻。元ログ行の無損失変換ではない。
SELECT $1:DEVICE_ID::VARCHAR AS DEVICE_ID,
       $1:VIEW_FROM::TIMESTAMP_NTZ AS VIEW_FROM,
       $1:VIEW_TO::TIMESTAMP_NTZ AS VIEW_TO
FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE/viewing_log_nw01.parquet
  (FILE_FORMAT => 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
LIMIT 5;

BEGIN
BEGIN TRANSACTION;
COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw01.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW02
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw02.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW03
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw03.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW04
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw04.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW05
  (EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE)
FROM (
  SELECT $1:EVENT_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:DEVICE_ID::VARCHAR,
         $1:VIEW_FROM::TIMESTAMP_NTZ, $1:VIEW_TO::TIMESTAMP_NTZ, $1:GENRE::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('viewing_log_nw05.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS
  (DEVICE_ID, LABEL_AVAILABLE, TARGET_F1)
FROM (
  SELECT $1:DEVICE_ID::VARCHAR, $1:LABEL_AVAILABLE::BOOLEAN,
         $1:TARGET_F1::INTEGER
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('device_labels.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.PROGRAM_MASTER
  (PROGRAM_ID, PROGRAM_NAME, NETWORK_ID, GENRE, TIME_SLOT, DURATION_MIN, SYNOPSIS)
FROM (
  SELECT $1:PROGRAM_ID::VARCHAR, $1:PROGRAM_NAME::VARCHAR, $1:NETWORK_ID::VARCHAR,
         $1:GENRE::VARCHAR, $1:TIME_SLOT::VARCHAR, $1:DURATION_MIN::NUMBER(4,0), $1:SYNOPSIS::VARCHAR
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('program_master.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;

COPY INTO BCAST_PLATFORM_HANDSON.RAW.PROGRAM_SCHEDULE
  (PROGRAM_ID, NETWORK_ID, AIR_DATE, AIR_FROM, AIR_TO)
FROM (
  SELECT $1:PROGRAM_ID::VARCHAR, $1:NETWORK_ID::VARCHAR, $1:AIR_DATE::DATE,
         $1:AIR_FROM::TIMESTAMP_NTZ, $1:AIR_TO::TIMESTAMP_NTZ
  FROM @BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_RAW_STAGE
)
FILES = ('program_schedule.parquet')
FILE_FORMAT = (FORMAT_NAME = 'BCAST_PLATFORM_HANDSON.INTEGRATIONS.BCAST_PLATFORM_PARQUET')
ON_ERROR = ABORT_STATEMENT FORCE = FALSE;
COMMIT;
EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    RAISE;
END;
END;
$$;

-- 実測件数。生成後の検証サマリーと照合し、旧サンプルの固定値を使わない。
SELECT 'NW01' AS SOURCE, COUNT(*) AS ROW_COUNT FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW01
UNION ALL SELECT 'NW02', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW02
UNION ALL SELECT 'NW03', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW03
UNION ALL SELECT 'NW04', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW04
UNION ALL SELECT 'NW05', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW05
UNION ALL SELECT 'DEVICE_LABELS', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS
UNION ALL SELECT 'PROGRAM_MASTER', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.PROGRAM_MASTER
UNION ALL SELECT 'PROGRAM_SCHEDULE', COUNT(*) FROM BCAST_PLATFORM_HANDSON.RAW.PROGRAM_SCHEDULE
ORDER BY SOURCE;

-- 合成TV世帯のF1在籍ラベル。視聴中の個人属性ではない。クラス別件数は実測する。
SELECT COUNT(DISTINCT DEVICE_ID) AS DEVICES,
       COUNT(*) - COUNT(DISTINCT DEVICE_ID) AS DUPLICATE_DEVICE_ROWS,
       COUNT_IF(LABEL_AVAILABLE) AS KNOWN_LABELS,
       COUNT_IF(NOT LABEL_AVAILABLE AND TARGET_F1 IS NULL) AS UNKNOWN_LABELS,
       COUNT_IF(LABEL_AVAILABLE AND TARGET_F1 = 0) AS CLASS_ZERO,
       COUNT_IF(LABEL_AVAILABLE AND TARGET_F1 = 1) AS CLASS_ONE,
       COUNT_IF(NOT LABEL_AVAILABLE AND TARGET_F1 IS NOT NULL) AS LEAKED_TARGETS,
       COUNT(DISTINCT DEVICE_ID) - 20000 AS COHORT_DIFFERENCE,
       COUNT_IF(LABEL_AVAILABLE) - 2000 AS PANEL_DIFFERENCE,
       COUNT_IF(NOT LABEL_AVAILABLE AND TARGET_F1 IS NULL) - 18000 AS UNLABELED_DIFFERENCE
FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS;