USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

SELECT COUNT(*) AS MART_ROWS, COUNT(DISTINCT DEVICE_ID) AS REACH_DEVICES,
       SUM(SESSION_COUNT) AS TOTAL_SESSIONS, SUM(VIEW_MINUTES) AS TOTAL_MINUTES
FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY;

WITH station_totals AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(SESSION_COUNT) AS SESSIONS, SUM(VIEW_MINUTES) AS MINUTES FROM BCAST_PLATFORM_HANDSON.NW01.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW02.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW03.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW04.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW05.MART_DEVICE_DAILY
), expected AS (
  SELECT SUM(ROWS_COUNT) AS ROWS_COUNT, SUM(SESSIONS) AS SESSIONS, SUM(MINUTES) AS MINUTES
  FROM station_totals
), actual AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(SESSION_COUNT) AS SESSIONS, SUM(VIEW_MINUTES) AS MINUTES
  FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY
)
SELECT actual.ROWS_COUNT - expected.ROWS_COUNT AS ROW_DIFFERENCE,
       actual.SESSIONS - expected.SESSIONS AS SESSION_DIFFERENCE,
       actual.MINUTES - expected.MINUTES AS MINUTE_DIFFERENCE
FROM actual CROSS JOIN expected;

WITH events (DEVICE_ID, GENRE, VIEW_MINUTES) AS (
  SELECT * FROM VALUES ('DEMO001', 'NEWS', 10), ('DEMO001', 'NEWS', 20), ('DEMO001', 'SPORTS', 15)
), mart AS (
  SELECT DEVICE_ID, GENRE, COUNT(*) AS SESSION_COUNT, SUM(VIEW_MINUTES) AS VIEW_MINUTES
  FROM events GROUP BY DEVICE_ID, GENRE
)
SELECT COUNT(*) AS MART_ROWS, SUM(SESSION_COUNT) AS TOTAL_SESSIONS,
       COUNT(DISTINCT DEVICE_ID) AS REACH_DEVICES, SUM(VIEW_MINUTES) AS TOTAL_MINUTES
FROM mart;