USE ROLE BCAST_PLATFORM_ENGINEER_ROLE;
USE WAREHOUSE BCAST_PLATFORM_COMMON_WH;

SELECT COUNT(*) AS MART_ROWS, COUNT(DISTINCT DEVICE_ID) AS REACH_DEVICES,
       SUM(SESSION_COUNT) AS TOTAL_SESSIONS, SUM(VIEW_MINUTES) AS TOTAL_MINUTES,
       MIN(VIEW_DATE) AS FIRST_DATE, MAX(VIEW_DATE) AS LAST_DATE,
       COUNT(DISTINCT GENRE) AS GENRES
FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY;

WITH station_totals AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(SESSION_COUNT) AS SESSIONS, SUM(VIEW_MINUTES) AS MINUTES FROM BCAST_PLATFORM_HANDSON.NW01.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW02.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW03.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW04.MART_DEVICE_DAILY
  UNION ALL
  SELECT COUNT(*), SUM(SESSION_COUNT), SUM(VIEW_MINUTES) FROM BCAST_PLATFORM_HANDSON.NW05.MART_DEVICE_DAILY
), expected AS (
  SELECT SUM(ROWS_COUNT) AS ROWS_COUNT, SUM(SESSIONS) AS SESSIONS, SUM(MINUTES) AS MINUTES
  FROM station_totals
), actual AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(SESSION_COUNT) AS SESSIONS, SUM(VIEW_MINUTES) AS MINUTES
  FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY
)
SELECT expected.ROWS_COUNT AS STATION_ROWS, actual.ROWS_COUNT AS COMMON_ROWS,
       expected.SESSIONS AS STATION_SESSIONS, actual.SESSIONS AS COMMON_SESSIONS,
       expected.MINUTES AS STATION_MINUTES, actual.MINUTES AS COMMON_MINUTES,
       actual.ROWS_COUNT - expected.ROWS_COUNT AS ROW_DIFFERENCE,
       actual.SESSIONS - expected.SESSIONS AS SESSION_DIFFERENCE,
       actual.MINUTES - expected.MINUTES AS MINUTE_DIFFERENCE
FROM actual CROSS JOIN expected;

WITH station_totals AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(VIEWING_DEVICES) AS DEVICE_MINUTES FROM BCAST_PLATFORM_HANDSON.NW01.MART_MINUTE_AUDIENCE
  UNION ALL SELECT COUNT(*), SUM(VIEWING_DEVICES) FROM BCAST_PLATFORM_HANDSON.NW02.MART_MINUTE_AUDIENCE
  UNION ALL SELECT COUNT(*), SUM(VIEWING_DEVICES) FROM BCAST_PLATFORM_HANDSON.NW03.MART_MINUTE_AUDIENCE
  UNION ALL SELECT COUNT(*), SUM(VIEWING_DEVICES) FROM BCAST_PLATFORM_HANDSON.NW04.MART_MINUTE_AUDIENCE
  UNION ALL SELECT COUNT(*), SUM(VIEWING_DEVICES) FROM BCAST_PLATFORM_HANDSON.NW05.MART_MINUTE_AUDIENCE
), expected AS (
  SELECT SUM(ROWS_COUNT) AS ROWS_COUNT, SUM(DEVICE_MINUTES) AS DEVICE_MINUTES FROM station_totals
), actual AS (
  SELECT COUNT(*) AS ROWS_COUNT, SUM(VIEWING_DEVICES) AS DEVICE_MINUTES
  FROM BCAST_PLATFORM_HANDSON.COMMON.MINUTE_AUDIENCE
)
SELECT expected.ROWS_COUNT AS STATION_ROWS, actual.ROWS_COUNT AS COMMON_ROWS,
       expected.DEVICE_MINUTES AS STATION_DEVICE_MINUTES, actual.DEVICE_MINUTES AS COMMON_DEVICE_MINUTES,
       actual.ROWS_COUNT - expected.ROWS_COUNT AS ROW_DIFFERENCE,
       actual.DEVICE_MINUTES - expected.DEVICE_MINUTES AS DEVICE_MINUTE_DIFFERENCE
FROM actual CROSS JOIN expected;

-- 局ごとに実測する。RAW全局UNIONやテーブル作成はしない。
-- *_DIFFERENCEは0を確認。FLOAT合計差は絶対1e-6または相対1e-9まで許容。
-- RAW件数は不正区間と完全重複を含む。生成後の検証サマリーとも照合する。
EXECUTE IMMEDIATE $$
DECLARE
  metrics ARRAY DEFAULT ARRAY_CONSTRUCT();
  raw_table VARCHAR;
  clean_table VARCHAR;
  daily_table VARCHAR;
  minutes_table VARCHAR;
  audience_table VARCHAR;
  station_metrics OBJECT;
  results RESULTSET;
BEGIN
  FOR station IN 1 TO 5 DO
    raw_table := 'BCAST_PLATFORM_HANDSON.RAW.VIEWING_LOG_NW0' || station;
    clean_table := 'BCAST_PLATFORM_HANDSON.NW0' || station || '.CLEAN_VIEWING';
    daily_table := 'BCAST_PLATFORM_HANDSON.NW0' || station || '.MART_DEVICE_DAILY';
    minutes_table := 'BCAST_PLATFORM_HANDSON.NW0' || station || '.VIEWING_MINUTES';
    audience_table := 'BCAST_PLATFORM_HANDSON.NW0' || station || '.MART_MINUTE_AUDIENCE';
    WITH raw_stats AS (
      SELECT COUNT(*) AS RAW_ROWS,
             COALESCE(COUNT_IF(VIEW_FROM IS NULL OR VIEW_TO IS NULL OR VIEW_TO <= VIEW_FROM
                      OR DATEDIFF('nanosecond', VIEW_FROM, VIEW_TO) > 86400000000000), 0) AS INVALID_ROWS
      FROM IDENTIFIER(:raw_table)
    ), valid_distinct AS (
      SELECT DISTINCT EVENT_ID, NETWORK_ID, DEVICE_ID, VIEW_FROM, VIEW_TO, GENRE
      FROM IDENTIFIER(:raw_table)
      WHERE VIEW_TO > VIEW_FROM AND DATEDIFF('nanosecond', VIEW_FROM, VIEW_TO) <= 86400000000000
    ), expected AS (
      SELECT COUNT(*) AS VALID_DISTINCT_ROWS,
             COALESCE(SUM(DATEDIFF('nanosecond', VIEW_FROM, VIEW_TO) / 60000000000.0), 0) AS ELAPSED_MINUTES,
             COALESCE(SUM(DATEDIFF('minute', DATE_TRUNC('minute', VIEW_FROM),
                                  DATE_TRUNC('minute', DATEADD('nanosecond', -1, VIEW_TO))) + 1), 0) AS EXPECTED_EXPANSION
      FROM valid_distinct
    ), clean AS (
      SELECT COUNT(*) AS CLEAN_ROWS, COUNT(DISTINCT DEVICE_ID) AS DEVICES,
             COUNT(DISTINCT GENRE) AS GENRES, COALESCE(SUM(VIEW_MINUTES), 0) AS CLEAN_MINUTES
      FROM IDENTIFIER(:clean_table)
    ), daily AS (
      SELECT COUNT(*) AS DAILY_ROWS, COALESCE(SUM(SESSION_COUNT), 0) AS SESSIONS,
             COALESCE(SUM(VIEW_MINUTES), 0) AS DAILY_MINUTES FROM IDENTIFIER(:daily_table)
    ), expanded AS (
      SELECT COUNT(*) AS EXPANDED_ROWS FROM IDENTIFIER(:minutes_table)
    ), distinct_device_minutes AS (
      SELECT COUNT(*) AS DISTINCT_DEVICE_MINUTES FROM (
        SELECT DISTINCT NETWORK_ID, DEVICE_ID, MINUTE_AT FROM IDENTIFIER(:minutes_table)
      )
    ), audience AS (
      SELECT COUNT(*) AS AUDIENCE_ROWS, COALESCE(SUM(VIEWING_DEVICES), 0) AS AUDIENCE_DEVICE_MINUTES
      FROM IDENTIFIER(:audience_table)
    )
    SELECT OBJECT_CONSTRUCT(
      'NETWORK_ID', 'NW0' || :station,
      'RAW_ROWS', raw_stats.RAW_ROWS, 'INVALID_ROWS', raw_stats.INVALID_ROWS,
      'VALID_DUPLICATE_ROWS', raw_stats.RAW_ROWS - raw_stats.INVALID_ROWS - expected.VALID_DISTINCT_ROWS,
      'EXPECTED_CLEAN_ROWS', expected.VALID_DISTINCT_ROWS, 'CLEAN_ROWS', clean.CLEAN_ROWS,
      'CLEAN_ROW_DIFFERENCE', clean.CLEAN_ROWS - expected.VALID_DISTINCT_ROWS,
      'DEVICES', clean.DEVICES, 'GENRES', clean.GENRES,
      'DAILY_ROWS', daily.DAILY_ROWS, 'SESSIONS', daily.SESSIONS,
      'SESSION_DIFFERENCE', daily.SESSIONS - clean.CLEAN_ROWS,
      'EXPECTED_ELAPSED_MINUTES', expected.ELAPSED_MINUTES, 'CLEAN_MINUTES', clean.CLEAN_MINUTES,
      'DAILY_MINUTES', daily.DAILY_MINUTES,
      'CLEAN_MINUTE_DIFFERENCE', clean.CLEAN_MINUTES - expected.ELAPSED_MINUTES,
      'DAILY_MINUTE_DIFFERENCE', daily.DAILY_MINUTES - clean.CLEAN_MINUTES,
      'EXPECTED_EXPANSION', expected.EXPECTED_EXPANSION, 'EXPANDED_ROWS', expanded.EXPANDED_ROWS,
      'EXPANSION_DIFFERENCE', expanded.EXPANDED_ROWS - expected.EXPECTED_EXPANSION,
      'AUDIENCE_ROWS', audience.AUDIENCE_ROWS,
      'DISTINCT_DEVICE_MINUTES', distinct_device_minutes.DISTINCT_DEVICE_MINUTES,
      'AUDIENCE_DEVICE_MINUTES', audience.AUDIENCE_DEVICE_MINUTES,
      'AUDIENCE_DIFFERENCE', audience.AUDIENCE_DEVICE_MINUTES - distinct_device_minutes.DISTINCT_DEVICE_MINUTES
    ) INTO :station_metrics
    FROM raw_stats CROSS JOIN expected CROSS JOIN clean CROSS JOIN daily CROSS JOIN expanded
    CROSS JOIN distinct_device_minutes CROSS JOIN audience;
    metrics := ARRAY_APPEND(metrics, station_metrics);
  END FOR;
  results := (SELECT VALUE:NETWORK_ID::VARCHAR AS NETWORK_ID, VALUE AS ACTUAL_METRICS
              FROM TABLE(FLATTEN(INPUT => :metrics)) ORDER BY NETWORK_ID);
  RETURN TABLE(results);
END;
$$;

-- 分内視聴端末数の総和は端末分数。全期間リーチや実視聴の経過分数とは別指標。
SELECT NETWORK_ID, VIEW_DATE, COUNT(*) AS OBSERVED_MINUTE_BUCKETS,
       MIN(MINUTE_AT) AS FIRST_MINUTE, MAX(MINUTE_AT) AS LAST_MINUTE,
       MAX(VIEWING_DEVICES) AS PEAK_MINUTE_DEVICES,
       SUM(VIEWING_DEVICES) AS DEVICE_MINUTE_BUCKETS
FROM BCAST_PLATFORM_HANDSON.COMMON.MINUTE_AUDIENCE
GROUP BY NETWORK_ID, VIEW_DATE ORDER BY VIEW_DATE, NETWORK_ID;

WITH observed AS (
  SELECT DISTINCT DEVICE_ID FROM BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY
)
SELECT COUNT_IF(observed.DEVICE_ID IS NULL) AS LABEL_DEVICES_WITHOUT_OBSERVATIONS,
       COUNT_IF(labels.DEVICE_ID IS NULL) AS OBSERVED_DEVICES_WITHOUT_LABEL_ROW
FROM BCAST_PLATFORM_HANDSON.RAW.DEVICE_LABELS AS labels
FULL OUTER JOIN observed ON labels.DEVICE_ID = observed.DEVICE_ID;