-- 任意の講師デモ: App Runtime用の権限を有償アカウントで準備します。
-- Snowflake App Runtimeはトライアルアカウントでは利用できません。
-- 現在の接続先が講師デモ用の有償アカウントであることを確認するまで実行しません。

SELECT CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT_NAME(), CURRENT_USER(), CURRENT_ROLE();

USE ROLE ACCOUNTADMIN;

-- Application ServiceとArtifact Repositoryを作る権限です。
GRANT CREATE APPLICATION SERVICE ON SCHEMA BCAST_PLATFORM_HANDSON.MART
  TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT CREATE ARTIFACT REPOSITORY ON SCHEMA BCAST_PLATFORM_HANDSON.MART
  TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;

-- Application Service所有者がダッシュボードデータを読む権限です。
GRANT USAGE ON SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA BCAST_PLATFORM_HANDSON.ML TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT SELECT ON TABLE BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT SELECT ON TABLE BCAST_PLATFORM_HANDSON.COMMON.MINUTE_AUDIENCE TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT SELECT ON TABLE BCAST_PLATFORM_HANDSON.ML.PREDICTIONS TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE BCAST_PLATFORM_COMMON_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;

-- Agent API routeは利用者のcaller’s rightsで動かします。
GRANT CALLER USAGE ON DATABASE BCAST_PLATFORM_HANDSON TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT CALLER USAGE ON SCHEMA BCAST_PLATFORM_HANDSON.MART TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT CALLER USAGE ON SCHEMA BCAST_PLATFORM_HANDSON.COMMON TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT CALLER USAGE ON WAREHOUSE BCAST_PLATFORM_COMMON_WH TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT CALLER USAGE ON AGENT BCAST_PLATFORM_HANDSON.MART.VIEWING_AGENT TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT CALLER SELECT ON SEMANTIC VIEW BCAST_PLATFORM_HANDSON.MART.SV_VIEWING TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
GRANT CALLER SELECT ON TABLE BCAST_PLATFORM_HANDSON.COMMON.VIEWING_DAILY TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;

-- Deploy後に実際のApplication Service名で共有します。
-- GRANT USAGE ON APPLICATION SERVICE BCAST_PLATFORM_HANDSON.MART.BCAST_VIEWING_INTELLIGENCE
--   TO ROLE BCAST_PLATFORM_ANALYST_ROLE;

SHOW CALLER GRANTS TO ROLE BCAST_PLATFORM_ENGINEER_ROLE;
